operator:
  image:
    repository: ghcr.io/sabinghost19/jit-access-platform-operator
    tag: v0.1.0
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001

  env:
    requestNamespace: default
    policiesConfigMap: jit-security-policies

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

replicaCount: 1

persistence:
  enabled: true
  existingClaim: ""
  size: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""

policiesConfigMap:
  create: true
  name: jit-security-policies
  blockedUsers:
    - "intern-test-user"
  antiAbuse:
    maxActiveSessions: 1
    cooldownMinutes: 15
    maxRequestsPerDay: 5
    maxDurationMinutes: 120

nodeSelector: {}
tolerations: []
affinity: {}
