{{- if and .Values.adminUI.enabled (not .Values.adminAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jit-access.fullname" . }}-admin-auth
  labels:
    {{- include "jit-access.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.adminAuth.username | quote }}
  password: {{ .Values.adminAuth.password | quote }}
{{- end }}
